In [ ]:

import os
from database_connect import mongo_operation as mongo

client_url= "mongodb+srv://shubham:Shubham@cluster0.oev8htd.mongodb.net/?retryWrites=true&w=majority"
database_name = "sensor"


def upload_files_to_mongodb(
    mongo_client_con_string,
    database_name,
    datasets_dir_name):
  
  for file in os.listdir(datasets_dir_name):
    if file.endswith('.csv'):
      file_name = file.split('.')[0]

      mongo_connection = mongo(
          client_url = mongo_client_con_string,
          database_name= database_name,
          collection_name= file_name
      )

      file_path = os.path.join(datasets_dir_name, file_name)
      mongo_connection.bulk_insert(file)
      print(f"{file_name} is uploaded to mongodb")


upload_files_to_mongodb(
    mongo_client_con_string= client_url,
    database_name = database_name,
    datasets_dir_name= "/content"
)

In [33]:

from pymongo.mongo_client import MongoClient
import pandas as pd
import json

In [34]:
#uniform resource identifier
uri = "mongodb+srv://shubham:Shubham@cluster0.oev8htd.mongodb.net/?retryWrites=true&w=majority"

In [35]:
# Create a new client and connect to the server
client = MongoClient(uri)

In [36]:
#create database name and collection name
DATABASE_NAME='ML_Project'
COLLECTION_NAME='wafer_fault'

In [37]:
# read data as an dataframe
df=pd.read_csv(r"D:\ML_Projects\sensor-fault-detection\notebooks\wafer_23012020_041211.csv")

In [38]:
df=df.drop("Unnamed: 0",axis=1)
df

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,-0.0279,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,0.0084,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,0.0138,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,-0.0046,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,-0.0046,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3013.66,2526.44,2185.2111,1141.6306,0.8447,100.0,100.5978,0.1217,1.5337,0.0090,...,NaN,0.5013,0.0076,0.0021,1.5152,0.0153,0.0048,0.0017,31.0176,-1
96,2982.87,2477.01,2315.2667,2360.1325,1.1259,100.0,90.1144,0.1160,1.4695,0.0071,...,NaN,0.5003,0.0106,0.0028,2.1263,0.0153,0.0048,0.0017,31.0176,1
97,3084.82,2387.42,2171.5000,1028.4440,0.7899,100.0,101.5122,0.1224,1.3603,-0.0031,...,NaN,0.5016,0.0130,0.0028,2.5865,0.0153,0.0048,0.0017,31.0176,-1
98,2955.87,2541.89,NaN,NaN,NaN,NaN,NaN,NaN,1.4493,-0.0194,...,NaN,0.5023,0.0140,0.0033,2.7810,0.0153,0.0048,0.0017,31.0176,-1
99,2914.86,2465.11,2210.2778,2120.5760,1.0700,100.0,95.1089,0.1230,1.5817,0.0118,...,NaN,0.5026,0.0121,0.0032,2.4064,0.0153,0.0048,0.0017,31.0176,1

In [39]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
Sensor-1,2968.3300,2961.0400,3072.0300,3021.8300,3006.9500,3003.7200,2953.5900,3086.5200,3048.7600,2984.0600,...,2964.6300,2990.5800,3007.0000,2982.1000,3091.7600,3013.6600,2982.8700,3084.8200,2955.8700,2914.8600
Sensor-2,2476.5800,2506.4300,2500.6800,2419.8300,2435.3400,2537.6600,2504.8600,2360.0400,2545.6800,2619.6000,...,2494.7500,2506.5600,2572.6200,2572.7800,2391.5600,2526.4400,2477.0100,2387.4200,2541.8900,2465.1100
Sensor-3,2216.7333,2170.0666,2205.7445,2205.7445,2189.8111,2210.7778,2224.6778,2204.2333,2224.6778,2225.0222,...,NaN,2194.3778,2213.2111,NaN,2315.2667,2185.2111,2315.2667,2171.5000,NaN,2210.2778
Sensor-4,1748.0885,1364.5157,1363.1048,1363.1048,1084.6502,2008.9216,1308.6479,2110.8288,1308.6479,1730.8480,...,NaN,1265.1715,2070.7147,NaN,2360.1325,1141.6306,2360.1325,1028.4440,NaN,2120.5760
Sensor-5,1.1127,1.5447,1.0518,1.0518,1.1993,1.1351,1.3907,1.6392,1.3907,1.5333,...,NaN,0.7588,1.9705,NaN,1.1259,0.8447,1.1259,0.7899,NaN,1.0700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sensor-587,0.0545,0.0545,0.0545,0.0545,0.0545,0.0099,0.0099,0.0099,0.0099,0.0128,...,0.0280,0.0195,0.0195,0.0195,0.0153,0.0153,0.0153,0.0153,0.0153,0.0153
Sensor-588,0.0184,0.0184,0.0184,0.0184,0.0184,0.0113,0.0113,0.0113,0.0113,0.0193,...,0.0078,0.0149,0.0149,0.0149,0.0048,0.0048,0.0048,0.0048,0.0048,0.0048
Sensor-589,0.0055,0.0055,0.0055,0.0055,0.0055,0.0038,0.0038,0.0038,0.0038,0.0060,...,0.0022,0.0047,0.0047,0.0047,0.0017,0.0017,0.0017,0.0017,0.0017,0.0017
Sensor-590,33.7876,33.7876,33.7876,33.7876,33.7876,114.2878,114.2878,114.2878,114.2878,151.1930,...,27.7601,76.0035,76.0035,76.0035,31.0176,31.0176,31.0176,31.0176,31.0176,31.0176
Good/Bad,-1.0000,1.0000,-1.0000,-1.0000,-1.0000,-1.0000,-1.0000,-1.0000,-1.0000,-1.0000,...,-1.0000,-1.0000,-1.0000,-1.0000,1.0000,-1.0000,1.0000,-1.0000,-1.0000,1.0000

In [40]:
json_record=list(json.loads(df.T.to_json()).values())

In [41]:
#now dump the data into database
client[DATABASE_NAME][COLLECTION_NAME].insert_many(json_record)